apiVersion: apps/v1
kind: Deployment
metadata:
    name: origo-core
    labels:
        app: origo-core
spec:
    replicas: 2
    selector:
        matchLabels:
            app: origo-core
    template:
        metadata:
            labels:
                app: origo-core
        spec:
            containers:
                - name: origo-core
                  image: origo/origo-core:1.0.1
                  imagePullPolicy: Never
                  ports:
                      - containerPort: 8080
