version: '3.2'

volumes:
  postgres_data:
      driver: local

services:
  postgres:
    image: postgres
    container_name: postgres
    volumes:
      - postgres_data:/var/lib/postgresql/data
    environment:
      POSTGRES_DB: keycloak
      POSTGRES_USER: keycloak
      POSTGRES_PASSWORD: password
    networks:
      - origo
    ports:
      - "5432:5432"
  
  keycloak:
    image: quay.io/keycloak/keycloak:latest
    container_name: keycloak
    command:
      - start-dev
    volumes:
      - ./providers:/opt/keycloak/providers:z
    environment:
      KC_DB_URL: jdbc:postgresql://postgres:5432/keycloak
      KC_DB_USERNAME: keycloak
      KC_DB_PASSWORD: password
      KC_DB: postgres
      KC_HOSTNAME: localhost
      KEYCLOAK_ADMIN: admin
      KEYCLOAK_ADMIN_PASSWORD: admin
    networks:
      - origo
    ports:
      - 8080:8080
    depends_on:
      - postgres
  
  origo-boot:
    image: origo/origo-core:1.0.1
    container_name: origo-core
    networks:
      - origo
    ports:
      - "8000:8000"
    depends_on:
      - postgres
      - keycloak

networks:
  origo:
    driver: bridge